# Site settings
title: "Webcamsteuerung mit Raspberry Pi"
#email:
#description:
#baseurl:
#url:
#twitter_username:
github_username: joker234
github_repo: fp_webcam

# Build settings
markdown: kramdown
permalink: pretty
